cfg:
  ctc_reduction: mean_batch
  decoder:
    _target_: nemo.collections.asr.modules.ConvASRDecoder
    feat_in: 512
    num_classes: 128
    vocabulary:
    - <unk>
    - ا
    - َ
    - ي
    - ر
    - م
    - ل
    - ▁ال
    - د
    - و
    - ت
    - ِ
    - ب
    - ع
    - ن
    - ْ
    - ة
    - ك
    - ه
    - س
    - ق
    - ُ
    - ف
    - ▁م
    - ح
    - َا
    - ▁و
    - ▁
    - ج
    - ▁ب
    - ▁ل
    - ▁أ
    - َّ
    - ص
    - ▁ت
    - ط
    - ش
    - ِي
    - خ
    - ذ
    - ▁ي
    - ▁ك
    - ض
    - ز
    - ث
    - ▁وَ
    - ▁في
    - أ
    - ▁إ
    - ان
    - ات
    - ال
    - ية
    - ▁الْ
    - ▁ا
    - ▁ه
    - ُو
    - ين
    - ▁أَ
    - ▁من
    - ▁الم
    - ى
    - ▁ح
    - نَ
    - ▁ع
    - غ
    - ئ
    - ▁ن
    - ▁ق
    - نْ
    - ▁ف
    - ▁س
    - اء
    - ِّ
    - ها
    - ▁أن
    - ار
    - لَ
    - ▁ش
    - إ
    - ٍ
    - ون
    - ▁ج
    - ▁الأ
    - ظ
    - نا
    - لا
    - ▁وال
    - ▁على
    - نَّ
    - َيْ
    - ▁ر
    - ▁د
    - آ
    - ▁الت
    - ▁خ
    - هُ
    - ٌ
    - ول
    - ▁بِ
    - ▁يَ
    - ست
    - اً
    - ًا
    - َةِ
    - ▁فِي
    - ▁يعني
    - ُّ
    - ْتَ
    - ▁تَ
    - ▁ص
    - ُونَ
    - ▁لل
    - ▁بال
    - ▁فَ
    - ▁الش
    - ▁عَ
    - ▁آه
    - ▁لِ
    - ّ
    - ▁عن
    - ▁ط
    - ▁مِنْ
    - َعْ
    - هُمْ
    - ؤ
    - ء
    - ً
  decoding:
    batch_dim_index: 0
    compute_timestamps: null
    ctc_timestamp_type: all
    greedy:
      compute_timestamps: false
      preserve_alignments: false
    preserve_alignments: null
    strategy: greedy
    word_seperator: ' '
  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    att_context_size:
    - -1
    - -1
    att_context_style: regular
    causal_downsampling: false
    conv_context_size: null
    conv_kernel_size: 31
    conv_norm_type: batch_norm
    d_model: 512
    dropout: 0.1
    dropout_att: 0.1
    dropout_emb: 0.0
    feat_in: 80
    feat_out: -1
    ff_expansion_factor: 4
    n_heads: 8
    n_layers: 18
    pos_emb_max_len: 5000
    self_attention_model: rel_pos
    subsampling: striding
    subsampling_conv_channels: -1
    subsampling_factor: 4
    untie_biases: true
    xscaling: true
  log_prediction: true
  nemo_version: 1.12.0
  optim:
    betas:
    - 0.9
    - 0.98
    lr: 1.0
    name: adamw
    sched:
      d_model: 512
      min_lr: 1.0e-06
      name: NoamAnnealing
      warmup_ratio: null
      warmup_steps: 10000
    weight_decay: 0.001
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    dither: 1.0e-05
    features: 80
    frame_splicing: 1
    log: true
    n_fft: 512
    normalize: per_feature
    pad_to: 0
    pad_value: 0.0
    sample_rate: 16000
    window: hann
    window_size: 0.025
    window_stride: 0.01
  sample_rate: 16000
  skip_nan_grad: false
  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2
    freq_width: 27
    time_masks: 10
    time_width: 0.05
  target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
  test_ds:
    batch_size: 16
    manifest_filepath: null
    num_workers: 8
    pin_memory: true
    sample_rate: 16000
    shuffle: false
    use_start_end_token: false
  tokenizer:
    dir: tokenizer_spe_unigram_v128
    model_path: nemo:b593e3ce74494014845d5e76182db2a1_tokenizer.model
    spe_tokenizer_vocab: nemo:5c6a007657a742659057ec7d3e3364c4_tokenizer.vocab
    type: bpe
    vocab_path: nemo:71f2df6ba4c74cc38c2138c6f130e77d_vocab.txt
  train_ds:
    batch_size: 32
    bucketing_batch_size: null
    bucketing_strategy: synced_randomized
    is_tarred: true
    manifest_filepath: null
    max_duration: 30.0
    min_duration: 0.1
    num_workers: 16
    pin_memory: true
    sample_rate: 16000
    shuffle: true
    shuffle_n: 2048
    tarred_audio_filepaths: null
    trim_silence: false
    use_start_end_token: false
  use_cer: true
  validation_ds:
    batch_size: 32
    manifest_filepath: null
    num_workers: 16
    pin_memory: true
    sample_rate: 16000
    shuffle: false
    use_start_end_token: false
