# python main.py --config-path="dataset_configs/arabic/youtube/" --config-name="config.yaml" processors_to_run="all"
# python main.py --config-path="dataset_configs/arabic/youtube/" --config-name="config.yaml" processors_to_run="all"

processors_to_run: "0:"
workspace_dir: /home/lgrigoryan/prog/asr_commonvoice_finetuning/NeMo-speech-data-processor/workdir
dataset_dir: /home/lgrigoryan/datasets/arab/
min_duration: 0.1 # minimal duration of the segment
max_duration: 40.0 # maximal duration of the segment
max_wer: 75.0 # maximal word error rate
max_cer: 30.0 # maximal char error rate

processors:
  - _target_: sdp.processors.CreateInitialManifestByExt
    raw_data_dir: ${dataset_dir}/audios
    extension: wav
    output_file_key: source_audio_path
    output_manifest_file: ${workspace_dir}/manifest0.json

  - _target_: sdp.processors.FfmpegConvert
    output_manifest_file: ${workspace_dir}/manifest1.json
    resampled_audio_dir: ${workspace_dir}/wav
    target_samplerate: 16000
    target_nchannels: 1
    input_file_key: source_audio_path
    output_file_key: sampled_audio_path

  - _target_: sdp.processors.CreateInitialManifestByExt
    raw_data_dir: ${dataset_dir}/subtitles
    extension: vtt
    output_file_key: subtitles_path
    output_manifest_file: ${workspace_dir}/manifest2.json

  - _target_: sdp.processors.MergeTwoManifests
    id_key1: subtitles_path
    id_key2: source_audio_path
    input_manifest_file2: ${workspace_dir}/manifest1.json
    output_manifest_file: ${workspace_dir}/manifest3.json

  - _target_: sdp.processors.GetAudioDuration
    output_manifest_file: ${workspace_dir}/manifest4.json
    audio_file_key: sampled_audio_path
    duration_key: sampled_audio_duration

  - _target_: sdp.processors.PreserveByValue
    output_manifest_file: ${workspace_dir}/manifest5.json
    input_value_key: sampled_audio_duration
    target_value: 0
    operator: gt

  - _target_: sdp.processors.datasets.commoncrawl.AllVttText 
    output_manifest_file: ${workspace_dir}/manifest6.json
    input_filepath_key: subtitles_path
    output_text_key: vtt_text


