# python main.py --config-path="dataset_configs/arabic/youtube/" --config-name="config_filter_quran.yaml"

processors_to_run: "0:"
workspace_dir: /home/lgrigoryan/prog/asr_commonvoice_finetuning/NeMo-speech-data-processor/workdir/quran
data_split: dev
dataset_dir: /home/lgrigoryan/datasets/arab_mcv

input_manifest_file: /home/lgrigoryan/prog/asr_commonvoice_finetuning/NeMo-speech-data-processor/workdir/wer/datasets_pc_diacr/mcv_dev/manifest_absolute.json

processors:
  - _target_: sdp.processors.ApplyLlama3
    input_manifest_file: ${input_manifest_file}
    pretrained_model: "meta-llama/Meta-Llama-3-8B-Instruct"
    input_text_key: "text"
    message: "You are searching quote in Quran answer \"yes\", chapter and verse, if text appears in quran, and \"no\" if not."
    torch_dtype: "float16"
    output_text_key: "is_from_quran"
    output_manifest_file: ${workspace_dir}/manifest7.json