# no punctuation, no tatweel, no diacritics, no dotted letters
# python main.py --config-path="dataset_configs/arabic/youtube/" --config-name="configmcv.yaml"

processors_to_run: "0:"

data_split: other
dataset_dir: /home/lgrigoryan/datasets/arab_mcv
workspace_dir: /home/lgrigoryan/prog/asr_commonvoice_finetuning/NeMo-speech-data-processor/workdir/mcv/${data_split}

processors:
  # 0 creating manifest {sample_id, audio_path}
  - _target_: sdp.processors.CreateInitialManifestMCV
    raw_data_dir: ${dataset_dir}
    extract_archive_dir: ${dataset_dir}
    resampled_audio_dir: ${workspace_dir}/clips_resampled
    data_split: ${data_split}
    language_id: ar
    already_extracted: True
    target_samplerate: 16000
    target_nchannels: 1
    output_manifest_file: ${workspace_dir}/manifest0.json

  # 1 normalizing arabic numbers
  - _target_: sdp.processors.NormalizeNumbers
    input_text_key: "text"
    output_text_key: "text"
    output_manifest_file: ${workspace_dir}/manifest1.json

  # 2 replacing punctuation marks
  - _target_: sdp.processors.SubRegex
    text_key: text
    regex_params_list:
      - { "pattern": "&lrm;", "repl": "" }
      - { "pattern": "&rlm;", "repl": "" }
      - { "pattern": "'", "repl": '' }
      - { "pattern": "’", "repl": '' }
      - { "pattern": "‘", "repl": '' }
      - { "pattern": "’", "repl": '' }
      - { "pattern": "‘", "repl": '' }
      - { "pattern": "٬", "repl": '' }
      - { "pattern": "\"", "repl": ''}
      - { "pattern": "…", "repl": ' '}
      - { "pattern": "«", "repl": ' ' }
      - { "pattern": "»", "repl": ' ' }
      - { "pattern": "“", "repl": ' ' }
      - { "pattern": "”", "repl": ' ' }
      - { "pattern": "☭", "repl": '' }
      - {"pattern": "\\s+", "repl": " "}
      - {"pattern": "\\[\\.\\]+", "repl": "."}
      - { "pattern": "\u0670", "repl": '' } # removing small alif
      - { "pattern": "\u06CC", "repl": "\u064A" } # replacing arabic letter farsi yeh with yeh
      - { "pattern": "\u06A9", "repl": "\u063A" } # replacing arabic letter keheh yeh with kaf
    output_manifest_file: ${workspace_dir}/manifest2.json

  # 3 replacing english punctuation marks with arabic ones
  - _target_: sdp.processors.SubRegex
    text_key: text
    regex_params_list:
      - { "pattern": ",", "repl": "،" }
      - { "pattern": "-", "repl": " " }
      - { "pattern": "؛", "repl": " " }
      - { "pattern": ";", "repl": " " }
      - { "pattern": " ،", "repl": "،" }
      - { "pattern": " \\.", "repl": "\\." }
      - { "pattern": " ؟", "repl": "؟" }
      - { "pattern": " :", "repl": ":" }
      - { "pattern": " !", "repl": "!" }
      - { "pattern": "\\s+", "repl": " "}
    output_manifest_file: ${workspace_dir}/manifest_2.json

  # 4 removing punctuation, diacritics, dotted letters and tatweel
  - _target_: sdp.processors.ArabicTextPreprocessor
    input_text_key: text
    remove_diacritics: True
    remove_punctuation: False
    normalize_dots: False
    remove_tatweel: True
    pyarabic_normalize: True
    reduce_diacritics: False
    output_manifest_file: ${workspace_dir}/manifest3.json

  # 5 dropping non alphabetical symbols
  - _target_: sdp.processors.DropNonAlphabet
    # alphabet: " \u0631\u0630\u062F\u062E\u062D\u062C\u062B\u062A\u0629\u0628\u0627\u0626\u0625\u0624\u0623\u0622\u0621\u064A\u0649\u0648\u0647\u0646\u0645\u0644\u0643\u0642\u0641\u063A\u0639\u0638\u0637\u0636\u0635\u0634\u0633\u0632\u064B\u064C\u064D\u064E\u064F\u0650\u0651\u0652"
    alphabet: ":،.! ؟  \u0631\u0630\u062F\u062E\u062D\u062C\u062B\u062A\u0629\u0628\u0627\u0626\u0625\u0624\u0623\u0622\u0621\u064A\u0649\u0648\u0647\u0646\u0645\u0644\u0643\u0642\u0641\u063A\u0639\u0638\u0637\u0636\u0635\u0634\u0633\u0632\u064B\u064C\u064D\u064E\u064F\u0650\u0651\u0652"
    output_manifest_file: ${workspace_dir}/manifest4.json
